### ISSUE TITLE
Shallow routing does not work

### ISSUE THREAD

**Issue by medihack** [isaachinman/next-i18next#1023]
## Describe the bug
When switching the location with shallow routing option (using the Link or Router) it is not working (language does not switch).

## Occurs in next-i18next version
Cloned from master branch (8.0.6).

## Steps to reproduce
Simply add `shallow={true}` to the [Link component in the example app](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L20)

## Expected behaviour
Change of language should also work with shallow routing

## OS (please complete the following information)
 - Browser: Chrome 88.0.4324.190

## Additional context
I can explain why this happens. With the current implementation of next-i18next the i18n instance is always completely replaced. The problem is that the `t` function of `useTranslation` is [cached](https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L45). So, if the components do not get recreated but just rerendered (as in shallow routing) the `t` is the old cached one even if the `I18nextProvider` has already a new i18n instance.

**Comment by medihack** [comment]
@isaachinman If [i18next/react-i18next#1273](https://github.com/i18next/react-i18next/pull/1273) gets merged there is still a little problem why shallow routing does not work for next-i18next. When using shallow routing then `getServerSideProps` won't be called again and `appWithTranslation` always uses a stale `initialLocale` to create the i18n client. To fix this the Next `router` must be queried for the correct locale. Here is a little code sample that would fix it in `appWithTranslation.js`:
```
const router = useRouter() // somewhere at the top
...
({ i18n } = createClient({
  ...createConfig({
    ...userConfig,
    lng: router.locale || initialLocale, // <- changed
  }),
  lng: router.locale || initialLocale, // <- changed
  resources: initialI18nStore,
}))
```

**Comment by isaachinman** [comment]
Sure, that looks reasonable.

**Comment by Dragomir-Ivanov** [comment]
Hi guys,
Any idea when this might be merged & released? Thanks!

**Comment by csinig** [comment]
Did this fix really solve completely the issue ?
I mean with the previous next/nextI18next versions, we were using i18n.changeLanguage which did not cause a complete app refresh.
Now the behaviour has changed using the router, and the whole app is re-rendering. Side effect is that some important components state is lot.
We thought shallowRouting could help, but it did not work, neither did it with this fix.
Did we miss something important, or maybe this issue isnt solved yet ?
Thanks

**Comment by isaachinman** [comment]
@csinig In `next-i18next` v8 and onwards, NextJs itself determines the locale, and all locale switching should be done through NextJs, not `i18n.changeLanguage`. The NextJs router controls the locale, and if you have a problem with the implementation, you should raise an issue on the NextJs repo.

**Comment by csinig** [comment]
@isaachinman Yes we are aware of that, implementation has changed and we already have adapted the code to use the nextJs router. 
We just thought that using shallowRouting=true would help to get back the previous behavior. 
If I understand this is not and won't be the case ?

**Comment by isaachinman** [comment]
@medihack Can you confirm if this issue is now resolved?

**Comment by medihack** [comment]
@isaachinman I can't say for sure as I am currently using a custom solution in the app I am creating. I could test it, but I will need some time. But just looking at the code it should work.

**Comment by isaachinman** [comment]
Sure, feel free to investigate and let me know if we need to reopen this.

**Comment by liho00** [comment]
@isaachinman  This issue still persists. Pls reopen it.
```
                <Link
                  href={router.asPath}
                  shallow
                  replace
                  locale={activeLocale === "zh-CN" ? "en-US" : "zh-CN"}
                >
                  <a className="text-white font-medium text-sm">
                    {activeLocale === "zh-CN" ? "中文" : "English"}
                  </a>
                </Link>
```
did not update the language, unless i remove the shallow.

**Comment by isaachinman** [comment]
@liho00 Did `router.locale` change? NextJs controls the locale itself, so I'm not sure what you're facing is an issue with `next-i18next`.

**Comment by csinig** [comment]
@isaachinman i dont think its an issue with nextjs. We faced the same issue as @liho00 and just ended but switching to next-translate witch just works fine with shallow

**Comment by isaachinman** [comment]
From the [docs]():

> Shallow routing allows you to change the URL without running data fetching methods again

`next-i18next` depends on those data fetching methods to provide translations as props to pages. If you'd like to use shallow routing with `next-i18next`, you'll need to follow [these guidelines](https://github.com/isaachinman/next-i18next#loading-namespaces-dynamically-client-side) for loading translations on the client side.

If anyone wants to work on a PR for shallow routing support, it would be much appreciated.

**Comment by isaachinman** [comment]
I suppose we can consider this a duplicate of #1532.
