### ISSUE TITLE
Using with `next-auth`: does serverSideTranslations() break useSession()?

### ISSUE THREAD

**Issue by markitics** [isaachinman/next-i18next#1680]
## Describe the bug
Using with [`next-auth.js`](https://next-auth.js.org/):
When logged in, if I click on a route with `serverSideTranslations`, the user appears signed out.  
Refreshing the page fixes the issue (no need to actually click "Sign in" again).

## Occurs in next-i18next version
`^10.2.0`

```json
  "dependencies": {
    "next": "^12.0.11-canary.4",
    "next-auth": "^4.2.1",
    "next-i18next": "^10.2.0",
    "nodemailer": "^6.6.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@types/node": "^17.0.14",
    "@types/react": "^17.0.39",
    "typescript": "^4.5.5"
  },
``` 

## Steps to reproduce
* Clone https://github.com/markitics/next-auth-with-i18n 
* Add `NEXTAUTH_SECRET`,  [`GITHUB_ID` and `GITHUB_SECRET`](https://next-auth.js.org/providers/github) in .env.local
* Log in; notice "Signed in as…" banner appear in `header.tsx`.
* Navigate to one of the "Translation" routes marked `/en` or `/de` (that's route `/en/with-await` or `/de/with-await`. 
   Note "Signed in as…" status has disappared. "Sign in" button available as user now appears logged out.
* Refresh the page to bring back the "Signed in as… " header (no need to actually click "Sign in" again).

## Expected behaviour
Clicking links such as /en or /de should not affect the "signed in" status of the user. 
<img width="690" alt="signed in banner" src="https://user-images.githubusercontent.com/855207/153426160-c39677a5-a0ab-43bb-89bc-f392a46c3f74.png">

## Screenshots
Actual behaviour:   
When I click on /en or /de links, the "Signed in as…" status changes to appear that the user is signed out. 
![translations-log-out](https://user-images.githubusercontent.com/855207/153425543-23c025f1-eebf-4038-ba88-a5635df79ec5.gif)

https://user-images.githubusercontent.com/855207/153428779-e4c05e17-d0a5-4c8b-b425-aee5ff18261d.mov

## OS (please complete the following information)
 - Device: MBP 2020 (M1)
 - Browser: Brave [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (arm64)]

## Additional context
* Code example:  
  https://github.com/markitics/next-auth-with-i18n 
  If you clone that repo and add a GITHUB_ID, GITHUB_SECRET and NEXTAUTH_SECRET, you should be able to have [log in with GitHub](https://next-auth.js.org/providers/github).

* This code example was motivated by a similar problem I had trying to add `next-i18next` to a current (production) project that uses `next-auth` v3. [StackOverflow question, unsolved](https://stackoverflow.com/questions/70974058/next-js-adding-next-i18next-to-a-project-that-uses-next-auth).

**Comment by gstrobl** [comment]
You need to pass the session to every page, I implemented wrapper like this:

```
export const withSession = (gssp) => {
  return async (context) => {
    const session = await getSession({ req: context.req });
    let headers = null;
    if (session?.accessToken) {
      headers = {
        headers: {
          Authorization: `Bearer ${session.accessToken}`,
        },
      };
    }

    return gssp(context, headers, session);
  };
};
```

then you can use it like this:

```
export const getServerSideProps = withSession(
  async (context, headers, session) => {
   ...
    return {
      props: {
        session,
        ...(await serverSideTranslations(context.locale, ['common'])),
      },
    };
  },
);
```

**Comment by isaachinman** [comment]
@markitics https://github.com/isaachinman/next-i18next/pull/1631 is now merged and released. Can you let me know if this issue remains?

**Comment by markitics** [comment]
@isaachinman @JonahLund yooo thank you so much, you absolute legends! YES, I can confirm that #1631 fixed it for me. I'm now using `next-i18next` v^10.3.0, and on every page I have either getServerSideProps or getStaticProps with
``` 
return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "optional_other_translation_files"])),
    },
  };
```

Everything's working great… thank you, heroes! 
https://twitter.com/awesoundapp/status/1493745687241969668

Thanks to your fix, I did NOT need to write my own `withSession` wrapper as proposed by @gstrobl (thanks for that suggestion, though!)

**Comment by Oliv6176** [comment]
@markitics Hmm I have just cloned your repo and the issue seems to persist. Can you confirm that #1631 solved the in your test repo?

**Comment by Oliv6176** [comment]
@isaachinman I seems like the issue is still there.... Should I create a new issue?
